# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the action occurred.",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email preserved for deleted users.",
                        max_length=254,
                        verbose_name="actor email",
                    ),
                ),
                (
                    "actor_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request.",
                        null=True,
                        verbose_name="actor IP",
                    ),
                ),
                (
                    "actor_user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device information.",
                        verbose_name="actor user agent",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("CatalogItem", "Catalog Item"),
                            ("ProductVariant", "Product Variant"),
                            ("Category", "Category"),
                            ("Tag", "Tag"),
                            ("Attribute", "Attribute"),
                            ("Order", "Order"),
                            ("OrderLine", "Order Line"),
                            ("Quote", "Quote"),
                            ("QuoteRequest", "Quote Request"),
                            ("QuoteLine", "Quote Line"),
                            ("Payment", "Payment"),
                            ("InventoryMovement", "Inventory Movement"),
                            ("User", "User"),
                            ("Role", "Role"),
                            ("Configuration", "Configuration"),
                            ("Content", "Content"),
                            ("Carousel", "Carousel"),
                            ("Branch", "Branch"),
                            ("FAQ", "FAQ"),
                            ("Testimonial", "Testimonial"),
                        ],
                        db_index=True,
                        help_text="Type of affected entity.",
                        max_length=50,
                        verbose_name="entity type",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of affected entity.",
                        max_length=100,
                        verbose_name="entity ID",
                    ),
                ),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable entity representation.",
                        max_length=255,
                        verbose_name="entity representation",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("state_changed", "State Changed"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_changed", "Password Changed"),
                            ("permission_changed", "Permission Changed"),
                            ("viewed", "Viewed"),
                            ("exported", "Exported"),
                            ("payment_processed", "Payment Processed"),
                            ("email_sent", "Email Sent"),
                        ],
                        db_index=True,
                        help_text="Action performed.",
                        max_length=30,
                        verbose_name="action",
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        blank=True,
                        help_text="JSON state before change.",
                        null=True,
                        verbose_name="before state",
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        blank=True,
                        help_text="JSON state after change.",
                        null=True,
                        verbose_name="after state",
                    ),
                ),
                (
                    "diff",
                    models.JSONField(
                        blank=True,
                        help_text="Calculated differences.",
                        null=True,
                        verbose_name="diff",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context and notes.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="audit_audit_actor_i_6355cc_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                ],
            },
        ),
    ]
