# Generated by Django 5.2.10 on 2026-01-21 08:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("sales", "Sales"),
                            ("operations", "Operations"),
                            ("customer", "Customer"),
                        ],
                        help_text="Unique role identifier.",
                        max_length=50,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable role name.",
                        max_length=100,
                        verbose_name="display name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of role capabilities.",
                        verbose_name="description",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object defining role permissions.",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted.",
                        verbose_name="is system role",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary email address used for authentication.",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="User's first name.",
                        max_length=150,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="User's last name.",
                        max_length=150,
                        verbose_name="last name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number.",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Required for legal compliance.",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user account is active.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can access the admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email.",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("es", "Spanish"), ("en", "English")],
                        default="es",
                        help_text="User's preferred language for communications.",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="User profile picture.",
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the last login.",
                        null=True,
                        verbose_name="last login IP",
                    ),
                ),
                (
                    "marketing_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user consented to receive marketing emails.",
                        verbose_name="marketing consent",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's role for access control.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms and Conditions"),
                            ("privacy", "Privacy Policy"),
                            ("cookies", "Cookie Policy"),
                            ("marketing", "Marketing Consent"),
                        ],
                        help_text="Type of legal document.",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        help_text="Version of the document accepted.",
                        max_length=20,
                        verbose_name="document version",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When consent was given.",
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address when consent was given.",
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device information.",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("registration", "During Registration"),
                            ("checkout", "During Checkout"),
                            ("banner", "Cookie Banner"),
                            ("settings", "Account Settings"),
                        ],
                        help_text="How consent was given.",
                        max_length=20,
                        verbose_name="consent method",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When consent was revoked (null if active).",
                        null=True,
                        verbose_name="revoked at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who gave consent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user consent",
                "verbose_name_plural": "user consents",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        help_text="Mexican tax ID (RFC).",
                        max_length=13,
                        verbose_name="RFC",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Legal business name (razón social).",
                        max_length=255,
                        verbose_name="business name",
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("601", "General de Ley Personas Morales"),
                            ("603", "Personas Morales con Fines no Lucrativos"),
                            (
                                "605",
                                "Sueldos y Salarios e Ingresos Asimilados a Salarios",
                            ),
                            ("606", "Arrendamiento"),
                            ("607", "Régimen de Enajenación o Adquisición de Bienes"),
                            ("608", "Demás ingresos"),
                            (
                                "610",
                                "Residentes en el Extranjero sin Establecimiento Permanente en México",
                            ),
                            ("611", "Ingresos por Dividendos"),
                            (
                                "612",
                                "Personas Físicas con Actividades Empresariales y Profesionales",
                            ),
                            ("614", "Ingresos por intereses"),
                            ("615", "Régimen de los ingresos por obtención de premios"),
                            ("616", "Sin obligaciones fiscales"),
                            ("620", "Sociedades Cooperativas de Producción"),
                            ("621", "Incorporación Fiscal"),
                            (
                                "622",
                                "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
                            ),
                            ("623", "Opcional para Grupos de Sociedades"),
                            ("624", "Coordinados"),
                            (
                                "625",
                                "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
                            ),
                            ("626", "Régimen Simplificado de Confianza"),
                        ],
                        help_text="Tax regime code.",
                        max_length=3,
                        verbose_name="tax regime",
                    ),
                ),
                (
                    "cfdi_use",
                    models.CharField(
                        choices=[
                            ("G01", "Adquisición de mercancías"),
                            ("G02", "Devoluciones, descuentos o bonificaciones"),
                            ("G03", "Gastos en general"),
                            ("I01", "Construcciones"),
                            ("I02", "Mobiliario y equipo de oficina por inversiones"),
                            ("I03", "Equipo de transporte"),
                            ("I04", "Equipo de cómputo y accesorios"),
                            ("I05", "Dados, troqueles, moldes, matrices y herramental"),
                            ("I06", "Comunicaciones telefónicas"),
                            ("I07", "Comunicaciones satelitales"),
                            ("I08", "Otra maquinaria y equipo"),
                            (
                                "D01",
                                "Honorarios médicos, dentales y gastos hospitalarios",
                            ),
                            ("D02", "Gastos médicos por incapacidad o discapacidad"),
                            ("D03", "Gastos funerales"),
                            ("D04", "Donativos"),
                            (
                                "D05",
                                "Intereses reales efectivamente pagados por créditos hipotecarios",
                            ),
                            ("D06", "Aportaciones voluntarias al SAR"),
                            ("D07", "Primas por seguros de gastos médicos"),
                            ("D08", "Gastos de transportación escolar obligatoria"),
                            ("D09", "Depósitos en cuentas para el ahorro"),
                            ("D10", "Pagos por servicios educativos"),
                            ("S01", "Sin efectos fiscales"),
                            ("CP01", "Pagos"),
                            ("CN01", "Nómina"),
                        ],
                        default="G03",
                        help_text="CFDI usage code.",
                        max_length=4,
                        verbose_name="CFDI use",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street name.", max_length=255, verbose_name="street"
                    ),
                ),
                (
                    "exterior_number",
                    models.CharField(
                        help_text="Exterior number.",
                        max_length=20,
                        verbose_name="exterior number",
                    ),
                ),
                (
                    "interior_number",
                    models.CharField(
                        blank=True,
                        help_text="Interior number (optional).",
                        max_length=20,
                        verbose_name="interior number",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        help_text="Neighborhood (colonia).",
                        max_length=100,
                        verbose_name="neighborhood",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City.", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State.", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code (5 digits).",
                        max_length=5,
                        verbose_name="postal code",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="MEX",
                        help_text="Country code (ISO 3166-1 alpha-3).",
                        max_length=3,
                        verbose_name="country",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default fiscal data.",
                        verbose_name="is default",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this fiscal data belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fiscal data",
                "verbose_name_plural": "fiscal data",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="users_fisca_user_id_3d7c0e_idx",
                    ),
                    models.Index(fields=["rfc"], name="users_fisca_rfc_be8c40_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_user_role_id_08cc48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["user", "document_type"], name="users_userc_user_id_51a934_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["document_type", "document_version"],
                name="users_userc_documen_2e42e5_idx",
            ),
        ),
    ]
