# Generated by Django 5.2.10 on 2026-02-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assignment_priority",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Assignment priority (1=highest, 5=lowest).",
                verbose_name="assignment priority",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_load",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of active quote requests assigned.",
                verbose_name="current load",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="max_load",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of active quote requests.",
                verbose_name="max load",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receives_auto_assignments",
            field=models.BooleanField(
                default=True,
                help_text="Whether this sales rep receives automatic assignments.",
                verbose_name="receives auto assignments",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sales_specialties",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of service category IDs this sales rep handles.",
                verbose_name="sales specialties",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("sales", "Sales"),
                    ("customer", "Customer"),
                    ("superadmin", "Super Administrator (Deprecated)"),
                    ("operations", "Operations (Deprecated)"),
                ],
                help_text="Unique role identifier.",
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
