# Generated by Django 5.2.11 on 2026-02-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_quote_system_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company or business name.",
                max_length=255,
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_delivery_address",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Default delivery address for quote requests.",
                verbose_name="default delivery address",
            ),
        ),
    ]
