# Generated by Django 5.2.11 on 2026-02-15 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_company_and_delivery_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Friendly label, e.g. "Oficina", "Casa".',
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                ("calle", models.CharField(max_length=255, verbose_name="street")),
                (
                    "numero_exterior",
                    models.CharField(max_length=50, verbose_name="exterior number"),
                ),
                (
                    "numero_interior",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="interior number",
                    ),
                ),
                (
                    "colonia",
                    models.CharField(max_length=255, verbose_name="neighborhood"),
                ),
                ("ciudad", models.CharField(max_length=255, verbose_name="city")),
                ("estado", models.CharField(max_length=255, verbose_name="state")),
                (
                    "codigo_postal",
                    models.CharField(max_length=10, verbose_name="postal code"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="reference"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default delivery address.",
                        verbose_name="default address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this address.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user address",
                "verbose_name_plural": "user addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
