# Generated by Django 5.2.10 on 2026-01-21 08:21

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Attribute name (e.g., Size, Material).",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Attribute name in English.",
                        max_length=100,
                        verbose_name="name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier.",
                        max_length=110,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("select", "Select (dropdown)"),
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes/No"),
                            ("color", "Color"),
                        ],
                        default="select",
                        help_text="Data type for this attribute.",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=True,
                        help_text="Show in catalog filters.",
                        verbose_name="is filterable",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show on product detail page.",
                        verbose_name="is visible",
                    ),
                ),
            ],
            options={
                "verbose_name": "attribute",
                "verbose_name_plural": "attributes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name.",
                        max_length=50,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier.",
                        max_length=60,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code (e.g., #FF5733).",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Display value.", max_length=100, verbose_name="value"
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        blank=True,
                        help_text="Value in English.",
                        max_length=100,
                        verbose_name="value (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier.",
                        max_length=110,
                        verbose_name="slug",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for color attributes.",
                        max_length=7,
                        verbose_name="color code",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order.", verbose_name="position"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Parent attribute.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "attribute value",
                "verbose_name_plural": "attribute values",
                "ordering": ["attribute", "position", "value"],
                "unique_together": {("attribute", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for search engines. Max 60 characters recommended.",
                        max_length=255,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description for search engines. Max 160 characters recommended.",
                        max_length=500,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO.",
                        max_length=255,
                        verbose_name="meta keywords",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing. Recommended size: 1200x630px.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name in Spanish.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Category name in English.",
                        max_length=100,
                        verbose_name="name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier.",
                        max_length=150,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Category description in Spanish.",
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Category description in English.",
                        verbose_name="description (English)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image.",
                        null=True,
                        upload_to="catalog/categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is visible.",
                        verbose_name="is active",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Parent category.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for search engines. Max 60 characters recommended.",
                        max_length=255,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description for search engines. Max 160 characters recommended.",
                        max_length=500,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO.",
                        max_length=255,
                        verbose_name="meta keywords",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing. Recommended size: 1200x630px.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "external_system",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name of the external ERP system.",
                        max_length=50,
                        verbose_name="external system",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of this record in the external system.",
                        max_length=100,
                        verbose_name="external ID",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync with external system.",
                        null=True,
                        verbose_name="last sync at",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                        ],
                        default="pending",
                        help_text="Current synchronization status.",
                        max_length=20,
                        verbose_name="sync status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("product", "Product"), ("service", "Service")],
                        default="product",
                        help_text="Item type: product or service.",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Item name in Spanish.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Item name in English.",
                        max_length=255,
                        verbose_name="name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier.",
                        max_length=280,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description for listings.",
                        max_length=500,
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        help_text="Brief description in English.",
                        max_length=500,
                        verbose_name="short description (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description in Spanish.",
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Full description in English.",
                        verbose_name="description (English)",
                    ),
                ),
                (
                    "sale_mode",
                    models.CharField(
                        choices=[
                            ("BUY", "Direct purchase"),
                            ("QUOTE", "Quote only"),
                            ("HYBRID", "Both"),
                        ],
                        default="BUY",
                        help_text="How this item can be purchased.",
                        max_length=10,
                        verbose_name="sale mode",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("FULL", "Full payment"),
                            ("DEPOSIT_ALLOWED", "Deposit allowed"),
                        ],
                        default="FULL",
                        help_text="Payment requirements for this item.",
                        max_length=20,
                        verbose_name="payment mode",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base price in MXN (for items without variants).",
                        max_digits=12,
                        null=True,
                        verbose_name="base price",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts.",
                        max_digits=12,
                        null=True,
                        verbose_name="compare at price",
                    ),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deposit percentage (e.g., 50.00 for 50%).",
                        max_digits=5,
                        null=True,
                        verbose_name="deposit percentage",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fixed deposit amount in MXN.",
                        max_digits=12,
                        null=True,
                        verbose_name="deposit amount",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to track stock for this item.",
                        verbose_name="track inventory",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this item is visible in catalog.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on homepage/featured sections.",
                        verbose_name="is featured",
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical specifications as JSON.",
                        verbose_name="specifications",
                    ),
                ),
                (
                    "installation_info",
                    models.TextField(
                        blank=True,
                        help_text="Installation information (if applicable).",
                        verbose_name="installation info",
                    ),
                ),
                (
                    "installation_info_en",
                    models.TextField(
                        blank=True,
                        help_text="Installation info in English.",
                        verbose_name="installation info (English)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="catalog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Associated tags.",
                        related_name="items",
                        to="catalog.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog item",
                "verbose_name_plural": "catalog items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "external_system",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name of the external ERP system.",
                        max_length=50,
                        verbose_name="external system",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of this record in the external system.",
                        max_length=100,
                        verbose_name="external ID",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync with external system.",
                        null=True,
                        verbose_name="last sync at",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                        ],
                        default="pending",
                        help_text="Current synchronization status.",
                        max_length=20,
                        verbose_name="sync status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit.",
                        max_length=100,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Variant name (e.g., "Blue, Large").',
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variant price in MXN.",
                        max_digits=12,
                        verbose_name="price",
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original price for showing discounts.",
                        max_digits=12,
                        null=True,
                        verbose_name="compare at price",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="Current stock level.",
                        verbose_name="stock",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=10,
                        help_text="Alert when stock falls below this level.",
                        verbose_name="low stock threshold",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg.",
                        max_digits=10,
                        null=True,
                        verbose_name="weight",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dimensions as JSON: {length, width, height, unit}.",
                        verbose_name="dimensions",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Barcode/UPC.",
                        max_length=50,
                        verbose_name="barcode",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variant is available.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "attribute_values",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Selected attribute values.",
                        related_name="variants",
                        to="catalog.attributevalue",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        help_text="Parent catalog item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.catalogitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "product variant",
                "verbose_name_plural": "product variants",
                "ordering": ["catalog_item", "sku"],
            },
        ),
        migrations.CreateModel(
            name="CatalogImage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product image.",
                        upload_to="catalog/products/",
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility alt text.",
                        max_length=255,
                        verbose_name="alt text",
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Alt text in English.",
                        max_length=255,
                        verbose_name="alt text (English)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the main image.",
                        verbose_name="is primary",
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        help_text="Parent catalog item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.catalogitem",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional variant-specific image.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "catalog image",
                "verbose_name_plural": "catalog images",
                "ordering": ["catalog_item", "-is_primary", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="catalog_pro_sku_187601_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["catalog_item", "is_active"],
                name="catalog_pro_catalog_24c047_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["stock"], name="catalog_pro_stock_bae480_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_084c2b_idx"),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["category", "is_active"], name="catalog_cat_categor_8a8a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["sale_mode", "is_active"], name="catalog_cat_sale_mo_674a58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="catalogitem",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="catalog_cat_is_feat_8b7cb3_idx",
            ),
        ),
    ]
