# Generated by Django 5.2.10 on 2026-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("product", "Product"), ("service", "Service")],
                default="product",
                help_text="Category type: product or service.",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
