# Generated by Django 5.2.11 on 2026-02-08 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="session ID",
                    ),
                ),
                ("page_url", models.URLField(max_length=2048, verbose_name="page URL")),
                (
                    "page_path",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="page path"
                    ),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="referrer"
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=128)),
                ("utm_medium", models.CharField(blank=True, max_length=128)),
                ("utm_campaign", models.CharField(blank=True, max_length=256)),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "screen_width",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "screen_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=128)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="timestamp"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time on page (ms)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "page view",
                "verbose_name_plural": "page views",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "page_path"],
                        name="analytics_p_timesta_8351e0_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="analytics_p_session_5e7fef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="event name"
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="event data"
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="page URL"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="track_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "track event",
                "verbose_name_plural": "track events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_name", "timestamp"],
                        name="analytics_t_event_n_81a4d6_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="analytics_t_session_ffd2b1_idx",
                    ),
                ],
            },
        ),
    ]
