# Generated by Django 5.2.11 on 2026-02-09 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("quote_request", "New Quote Request"),
                            ("quote_sent", "Quote Sent"),
                            ("quote_accepted", "Quote Accepted"),
                            ("quote_rejected", "Quote Rejected"),
                            ("change_request", "Change Request"),
                            ("order_created", "Order Created"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="entity type"
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="entity id"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="action url"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                ],
            },
        ),
    ]
