# Generated by Django 5.2.11 on 2026-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("quote_request", "New Quote Request"),
                    ("quote_sent", "Quote Sent"),
                    ("quote_accepted", "Quote Accepted"),
                    ("quote_rejected", "Quote Rejected"),
                    ("change_request", "Change Request"),
                    ("order_created", "Order Created"),
                    ("order_status", "Order Status Changed"),
                    ("order_completed", "Order Completed"),
                    ("payment_received", "Payment Received"),
                    ("new_user", "New User Registered"),
                    ("catalog_purchase", "Catalog Purchase"),
                    ("quote_expiring", "Quote Expiring Soon"),
                    ("request_unattended", "Request Unattended"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
                verbose_name="type",
            ),
        ),
    ]
