# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("mercadopago", "Mercado Pago"), ("paypal", "PayPal")],
                        help_text="Payment provider.",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of webhook event.",
                        max_length=100,
                        verbose_name="event type",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event ID from provider.",
                        max_length=100,
                        verbose_name="event ID",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Raw webhook payload.", verbose_name="payload"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request headers.",
                        verbose_name="headers",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether event was processed.",
                        verbose_name="processed",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error during processing.",
                        verbose_name="processing error",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Webhook source IP.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment webhook log",
                "verbose_name_plural": "payment webhook logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Refund amount.",
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("duplicate", "Duplicate Payment"),
                            ("fraud", "Fraudulent Transaction"),
                            ("order_cancelled", "Order Cancelled"),
                            ("product_issue", "Product/Service Issue"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for refund.",
                        max_length=30,
                        verbose_name="reason",
                    ),
                ),
                (
                    "reason_details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about refund reason.",
                        verbose_name="reason details",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Refund status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="External refund ID from provider.",
                        max_length=100,
                        verbose_name="provider refund ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When refund was processed.",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional refund data.",
                        verbose_name="metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("mercadopago", "Mercado Pago"), ("paypal", "PayPal")],
                        help_text="Payment provider.",
                        max_length=20,
                        verbose_name="provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("in_process", "In Process"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Payment status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount.",
                        max_digits=12,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN",
                        help_text="Currency code.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Provider fee amount.",
                        max_digits=12,
                        null=True,
                        verbose_name="fee amount",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Net amount after fees.",
                        max_digits=12,
                        null=True,
                        verbose_name="net amount",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External payment ID from provider.",
                        max_length=100,
                        verbose_name="provider payment ID",
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External order/preference ID.",
                        max_length=100,
                        verbose_name="provider order ID",
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of payment method (credit_card, debit_card, etc.).",
                        max_length=50,
                        verbose_name="payment method type",
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="Specific payment method (visa, mastercard, etc.).",
                        max_length=50,
                        verbose_name="payment method ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment data from provider.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if payment failed.",
                        verbose_name="error message",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Customer IP address.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was approved.",
                        null=True,
                        verbose_name="approved at",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related order.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
