# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Related quote.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="quotes.quote",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                help_text="User who made payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhooklog",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Related payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_logs",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="payment",
            field=models.ForeignKey(
                help_text="Original payment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="processed_by",
            field=models.ForeignKey(
                help_text="User who processed refund.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_payment_id"], name="payments_pa_provide_adf74c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_pa_order_i_a76289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["event_id"], name="payments_pa_event_i_94f167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["provider", "event_type"], name="payments_pa_provide_ecd09e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["processed", "created_at"],
                name="payments_pa_process_acb39f_idx",
            ),
        ),
    ]
