# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        help_text="Type of movement.",
                        max_length=20,
                        verbose_name="movement type",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity changed (positive for IN, negative for OUT).",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase from Supplier"),
                            ("return", "Customer Return"),
                            ("production", "Internal Production"),
                            ("transfer_in", "Transfer In"),
                            ("sale", "Sale"),
                            ("internal_use", "Internal Use"),
                            ("damaged", "Damaged/Defective"),
                            ("expired", "Expired"),
                            ("lost", "Lost/Missing"),
                            ("transfer_out", "Transfer Out"),
                            ("inventory_count", "Inventory Count"),
                            ("correction", "Error Correction"),
                            ("initial", "Initial Stock"),
                        ],
                        help_text="Reason for movement.",
                        max_length=50,
                        verbose_name="reason",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("order_line", "Order Line"),
                            ("quote", "Quote"),
                            ("purchase_order", "Purchase Order"),
                            ("manual", "Manual Entry"),
                            ("system", "System Generated"),
                        ],
                        default="manual",
                        help_text="Type of reference document.",
                        max_length=20,
                        verbose_name="reference type",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of reference document.",
                        max_length=100,
                        verbose_name="reference ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes.", verbose_name="notes"
                    ),
                ),
                (
                    "stock_before",
                    models.IntegerField(
                        help_text="Stock level before movement.",
                        verbose_name="stock before",
                    ),
                ),
                (
                    "stock_after",
                    models.IntegerField(
                        help_text="Stock level after movement.",
                        verbose_name="stock after",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created movement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Product variant affected.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventory movement",
                "verbose_name_plural": "inventory movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "created_at"],
                        name="inventory_i_variant_b826d6_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "created_at"],
                        name="inventory_i_movemen_7bd8e8_idx",
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="inventory_i_referen_0d8590_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "threshold",
                    models.IntegerField(
                        help_text="Stock threshold that triggered alert.",
                        verbose_name="threshold",
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(
                        help_text="Stock level when alert was created.",
                        verbose_name="current stock",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Alert status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When alert was acknowledged.",
                        null=True,
                        verbose_name="acknowledged at",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When alert was resolved.",
                        null=True,
                        verbose_name="resolved at",
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether notification email was sent.",
                        verbose_name="notification sent",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who acknowledged alert.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Product variant with low stock.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock alert",
                "verbose_name_plural": "stock alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="inventory_s_status_79785d_idx",
                    ),
                    models.Index(
                        fields=["variant", "status"],
                        name="inventory_s_variant_4ecc2e_idx",
                    ),
                ],
            },
        ),
    ]
