# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Lead's full name.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Lead's email address.",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Lead's phone number.",
                        max_length=20,
                        verbose_name="phone",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Lead's company.",
                        max_length=255,
                        verbose_name="company",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact_form", "Contact Form"),
                            ("chatbot", "Chatbot"),
                            ("quote_request", "Quote Request"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone Call"),
                            ("referral", "Referral"),
                            ("other", "Other"),
                        ],
                        default="contact_form",
                        help_text="Where lead came from.",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        help_text="Lead status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Initial message from lead.",
                        verbose_name="message",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes.", verbose_name="notes"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Lead's IP address.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/device info.",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        help_text="Marketing UTM source.",
                        max_length=100,
                        verbose_name="UTM source",
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        help_text="Marketing UTM medium.",
                        max_length=100,
                        verbose_name="UTM medium",
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True,
                        help_text="Marketing UTM campaign.",
                        max_length=100,
                        verbose_name="UTM campaign",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned sales rep.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Converted user account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique session identifier.",
                        max_length=100,
                        unique=True,
                        verbose_name="session ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("web", "Web Chat"), ("whatsapp", "WhatsApp")],
                        default="web",
                        help_text="Conversation channel.",
                        max_length=20,
                        verbose_name="channel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("waiting", "Waiting for Response"),
                            ("escalated", "Escalated to Human"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        help_text="Conversation status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "escalated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When conversation was escalated.",
                        null=True,
                        verbose_name="escalated at",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When conversation was closed.",
                        null=True,
                        verbose_name="closed at",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional session data.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Human agent handling escalation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lead.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="chatbot.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("bot", "Bot"),
                            ("agent", "Human Agent"),
                            ("system", "System"),
                        ],
                        help_text="Message sender role.",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content.", verbose_name="content"
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="Detected intent.",
                        max_length=100,
                        verbose_name="intent",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Intent detection confidence.",
                        null=True,
                        verbose_name="confidence",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional message data.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Parent conversation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="chatbot_lea_email_bc222b_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "created_at"], name="chatbot_lea_status_fccefb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["source", "created_at"], name="chatbot_lea_source_74e3f4_idx"
            ),
        ),
    ]
