# Generated by Django 5.2.11 on 2026-02-10 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        help_text="Positive or negative rating.",
                        max_length=10,
                        verbose_name="rating",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional text feedback from user.",
                        verbose_name="comment",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Chat session for anonymous tracking.",
                        max_length=100,
                        verbose_name="session ID",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        help_text="The bot message being rated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chatbot.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "message feedback",
                "verbose_name_plural": "message feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
