# Generated by Django 5.2.10 on 2026-01-21 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch name.", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street address.",
                        max_length=255,
                        verbose_name="street",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        help_text="Neighborhood (colonia).",
                        max_length=100,
                        verbose_name="neighborhood",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City.", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State.", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code.",
                        max_length=10,
                        verbose_name="postal code",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone number(s).",
                        max_length=100,
                        verbose_name="phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email.", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "hours",
                    models.TextField(
                        help_text="Operating hours in Spanish.", verbose_name="hours"
                    ),
                ),
                (
                    "hours_en",
                    models.TextField(
                        blank=True,
                        help_text="Operating hours in English.",
                        verbose_name="hours (English)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Map latitude coordinate.",
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Map longitude coordinate.",
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to Google Maps.",
                        verbose_name="Google Maps URL",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Branch photo.",
                        null=True,
                        upload_to="content/branches/",
                        verbose_name="image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether branch is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch",
                "verbose_name_plural": "branches",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Slide title in Spanish.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Slide title in English.",
                        max_length=255,
                        verbose_name="title (English)",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Slide subtitle in Spanish.",
                        max_length=500,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True,
                        help_text="Slide subtitle in English.",
                        max_length=500,
                        verbose_name="subtitle (English)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Slide image. Recommended: 1920x800px.",
                        upload_to="content/carousel/",
                        verbose_name="image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional mobile-specific image.",
                        null=True,
                        upload_to="content/carousel/mobile/",
                        verbose_name="mobile image",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Call-to-action button text.",
                        max_length=50,
                        verbose_name="CTA text",
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        blank=True,
                        help_text="CTA text in English.",
                        max_length=50,
                        verbose_name="CTA text (English)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="CTA button link (internal or external).",
                        max_length=255,
                        verbose_name="CTA URL",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether slide is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "carousel slide",
                "verbose_name_plural": "carousel slides",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ClientLogo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Client company name.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        help_text="Company logo. Recommended: transparent PNG.",
                        upload_to="content/clients/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Client website URL.",
                        verbose_name="website",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether logo is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "client logo",
                "verbose_name_plural": "client logos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Question in Spanish.",
                        max_length=500,
                        verbose_name="question",
                    ),
                ),
                (
                    "question_en",
                    models.CharField(
                        blank=True,
                        help_text="Question in English.",
                        max_length=500,
                        verbose_name="question (English)",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Answer in Spanish.", verbose_name="answer"
                    ),
                ),
                (
                    "answer_en",
                    models.TextField(
                        blank=True,
                        help_text="Answer in English.",
                        verbose_name="answer (English)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("products", "Products & Services"),
                            ("orders", "Orders & Delivery"),
                            ("payments", "Payments"),
                            ("quotes", "Quotes"),
                            ("support", "Support"),
                        ],
                        default="general",
                        help_text="FAQ category.",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether FAQ is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "position"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Agencia MCD",
                        help_text="Site name.",
                        max_length=100,
                        verbose_name="site name",
                    ),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        blank=True,
                        help_text="Site name in English.",
                        max_length=100,
                        verbose_name="site name (English)",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Site tagline in Spanish.",
                        max_length=255,
                        verbose_name="tagline",
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        blank=True,
                        help_text="Site tagline in English.",
                        max_length=255,
                        verbose_name="tagline (English)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Main contact email.",
                        max_length=254,
                        verbose_name="contact email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="Main contact phone.",
                        max_length=20,
                        verbose_name="contact phone",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number for chat.",
                        max_length=20,
                        verbose_name="WhatsApp number",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Social media links as JSON.",
                        verbose_name="social links",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Site logo.",
                        null=True,
                        upload_to="content/branding/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        help_text="Logo for dark backgrounds.",
                        null=True,
                        upload_to="content/branding/",
                        verbose_name="logo (dark)",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Site favicon.",
                        null=True,
                        upload_to="content/branding/",
                        verbose_name="favicon",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="GA4 Measurement ID.",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "meta_pixel_id",
                    models.CharField(
                        blank=True,
                        help_text="Facebook/Meta Pixel ID.",
                        max_length=50,
                        verbose_name="Meta Pixel ID",
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Tag Manager ID.",
                        max_length=50,
                        verbose_name="GTM ID",
                    ),
                ),
                (
                    "about_content",
                    models.TextField(
                        blank=True,
                        help_text="About section content in Spanish.",
                        verbose_name="about content",
                    ),
                ),
                (
                    "about_content_en",
                    models.TextField(
                        blank=True,
                        help_text="About section content in English.",
                        verbose_name="about content (English)",
                    ),
                ),
                (
                    "mission",
                    models.TextField(
                        blank=True,
                        help_text="Company mission in Spanish.",
                        verbose_name="mission",
                    ),
                ),
                (
                    "mission_en",
                    models.TextField(
                        blank=True,
                        help_text="Company mission in English.",
                        verbose_name="mission (English)",
                    ),
                ),
                (
                    "vision",
                    models.TextField(
                        blank=True,
                        help_text="Company vision in Spanish.",
                        verbose_name="vision",
                    ),
                ),
                (
                    "vision_en",
                    models.TextField(
                        blank=True,
                        help_text="Company vision in English.",
                        verbose_name="vision (English)",
                    ),
                ),
                (
                    "values",
                    models.TextField(
                        blank=True,
                        help_text="Company values in Spanish.",
                        verbose_name="values",
                    ),
                ),
                (
                    "values_en",
                    models.TextField(
                        blank=True,
                        help_text="Company values in English.",
                        verbose_name="values (English)",
                    ),
                ),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        help_text="Author's full name.",
                        max_length=100,
                        verbose_name="author name",
                    ),
                ),
                (
                    "author_title",
                    models.CharField(
                        blank=True,
                        help_text="Author's job title.",
                        max_length=100,
                        verbose_name="author title",
                    ),
                ),
                (
                    "author_company",
                    models.CharField(
                        blank=True,
                        help_text="Author's company name.",
                        max_length=100,
                        verbose_name="author company",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Testimonial text in Spanish.", verbose_name="content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Testimonial text in English.",
                        verbose_name="content (English)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Author's photo.",
                        null=True,
                        upload_to="content/testimonials/",
                        verbose_name="photo",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="Star rating (1-5).",
                        null=True,
                        verbose_name="rating",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether testimonial is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "testimonial",
                "verbose_name_plural": "testimonials",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title for search engines. Max 60 characters recommended.",
                        max_length=255,
                        verbose_name="meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="SEO description for search engines. Max 160 characters recommended.",
                        max_length=500,
                        verbose_name="meta description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for SEO.",
                        max_length=255,
                        verbose_name="meta keywords",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image for social media sharing. Recommended size: 1200x630px.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms and Conditions"),
                            ("privacy", "Privacy Policy"),
                            ("cookies", "Cookie Policy"),
                            ("legal", "Legal Notice"),
                        ],
                        help_text="Document type.",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title in Spanish.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Page title in English.",
                        max_length=255,
                        verbose_name="title (English)",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Page content in Spanish (supports Markdown).",
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Page content in English (supports Markdown).",
                        verbose_name="content (English)",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Document version (e.g., 1.0, 1.1).",
                        max_length=20,
                        verbose_name="version",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="When this version becomes effective.",
                        verbose_name="effective date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the active version.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal page",
                "verbose_name_plural": "legal pages",
                "ordering": ["type", "-effective_date"],
                "unique_together": {("type", "version")},
            },
        ),
    ]
