# Generated by Django 5.2.10 on 2026-01-22 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name in Spanish.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        help_text="Service name in English.",
                        max_length=100,
                        verbose_name="name (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Service description in Spanish.",
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Service description in English.",
                        verbose_name="description (English)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon identifier (e.g., "printer", "truck", "photo").',
                        max_length=100,
                        verbose_name="icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Service image.",
                        null=True,
                        upload_to="content/services/",
                        verbose_name="image",
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Starting price (optional).",
                        max_digits=10,
                        null=True,
                        verbose_name="price from",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        default="Cotizar",
                        help_text="Call-to-action button text.",
                        max_length=50,
                        verbose_name="CTA text",
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        blank=True,
                        default="Quote",
                        help_text="CTA text in English.",
                        max_length=50,
                        verbose_name="CTA text (English)",
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        default="#cotizar",
                        help_text="CTA button link.",
                        max_length=255,
                        verbose_name="CTA URL",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show in featured services section.",
                        verbose_name="is featured",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether service is visible.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ["position"],
            },
        ),
    ]
