# Generated by Django 5.2.10 on 2026-02-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_serviceimage_portfoliovideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselslide",
            name="service_key",
            field=models.CharField(
                blank=True,
                help_text='Quote service identifier (e.g. "espectaculares"). Links slide to a quotable service.',
                max_length=50,
                verbose_name="service key",
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="subtype_key",
            field=models.CharField(
                blank=True,
                help_text='Service subtype key for quote form linking (e.g. "letras-3d").',
                max_length=100,
                verbose_name="subtype key",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when this record was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether video is visible on the landing page.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="orientation",
            field=models.CharField(
                choices=[
                    ("vertical", "Vertical (9:16) — Shorts/Reels"),
                    ("horizontal", "Horizontal (16:9) — Standard"),
                ],
                default="vertical",
                help_text="Video aspect ratio.",
                max_length=20,
                verbose_name="orientation",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Display order. Lower values appear first.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Video label in Spanish (shown below the video).",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Video label in English.",
                max_length=255,
                verbose_name="title (English)",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this record was last updated.",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovideo",
            name="youtube_id",
            field=models.CharField(
                help_text="The video ID from the YouTube URL. E.g. for https://youtube.com/shorts/sqOb-gSSQq8 → sqOb-gSSQq8",
                max_length=20,
                verbose_name="YouTube video ID",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Image alt text in Spanish.",
                max_length=255,
                verbose_name="alt text",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="alt_text_en",
            field=models.CharField(
                blank=True,
                help_text="Image alt text in English.",
                max_length=255,
                verbose_name="alt text (English)",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when this record was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether image is visible on the landing page.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Display order. Lower values appear first.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this record was last updated.",
                verbose_name="updated at",
            ),
        ),
    ]
