# Generated by Django 5.2.10 on 2026-02-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_add_service_key_subtype_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_key",
            field=models.CharField(
                blank=True,
                help_text='Unique service identifier (e.g. "espectaculares"). Links to the quote form service.',
                max_length=50,
                null=True,
                unique=True,
                verbose_name="service key",
            ),
        ),
    ]
