# Generated by Django 5.2.10 on 2026-03-20 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_serviceimage_display_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Display order. Lower values appear first.",
                        verbose_name="position",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "YouTube Video")],
                        default="image",
                        help_text="Whether this item is an image or video.",
                        max_length=20,
                        verbose_name="media type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded image. Required for image type items. Max 5 MB.",
                        null=True,
                        upload_to="content/portfolio/",
                        verbose_name="image",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        blank=True,
                        help_text='YouTube video ID (e.g., "sqOb-gSSQq8"). Required for video type items.',
                        max_length=20,
                        verbose_name="YouTube video ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Item title/label in Spanish.",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Item title/label in English.",
                        max_length=255,
                        verbose_name="title (English)",
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("landscape_16_9", "Landscape (16:9)"),
                            ("portrait_reel_9_16", "Portrait Reel (9:16)"),
                        ],
                        default="landscape_16_9",
                        help_text="Display aspect ratio on landing page.",
                        max_length=20,
                        verbose_name="aspect ratio",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is visible on the landing page.",
                        verbose_name="is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "portfolio item",
                "verbose_name_plural": "portfolio items",
                "ordering": ["position"],
            },
        ),
    ]
