# Generated by Django 5.2.14 on 2026-08-19 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_promobanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="promobanner",
            name="background_color_secondary",
            field=models.CharField(
                blank=True,
                help_text="Second gradient color. Only used when the background style is a gradient.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="second background color",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="background_style",
            field=models.CharField(
                choices=[("solid", "Solid color"), ("gradient", "Gradient")],
                default="solid",
                max_length=20,
                verbose_name="background style",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="badge_background_color",
            field=models.CharField(
                blank=True,
                help_text="Leave empty for a translucent dark badge.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="badge background color",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="badge_shape",
            field=models.CharField(
                choices=[
                    ("pill", "Pill"),
                    ("rounded", "Rounded"),
                    ("square", "Square"),
                ],
                default="rounded",
                max_length=20,
                verbose_name="badge shape",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="badge_text_color",
            field=models.CharField(
                blank=True,
                help_text="Leave empty to reuse the title color.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="badge text color",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="border_color",
            field=models.CharField(
                blank=True,
                help_text="Leave empty for the default subtle border.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="border color",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("sans", "Inter (sans)"),
                    ("display", "Montserrat (display)"),
                    ("mono", "Fira Code (mono)"),
                ],
                default="sans",
                max_length=20,
                verbose_name="font family",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="gradient_direction",
            field=models.CharField(
                choices=[
                    ("to right", "Left to right"),
                    ("to left", "Right to left"),
                    ("to bottom", "Top to bottom"),
                    ("135deg", "Diagonal"),
                ],
                default="to right",
                max_length=20,
                verbose_name="gradient direction",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="subtitle_color",
            field=models.CharField(
                blank=True,
                help_text="Leave empty to reuse the title color at reduced opacity.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="subtitle color",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="text_transform",
            field=models.CharField(
                choices=[
                    ("none", "As typed"),
                    ("uppercase", "UPPERCASE"),
                    ("capitalize", "Capitalized"),
                ],
                default="none",
                max_length=20,
                verbose_name="text transform",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="title_size",
            field=models.CharField(
                choices=[
                    ("sm", "Small"),
                    ("base", "Medium"),
                    ("lg", "Large"),
                    ("xl", "Extra large"),
                ],
                default="sm",
                max_length=10,
                verbose_name="title size",
            ),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="title_weight",
            field=models.CharField(
                choices=[
                    ("medium", "Medium"),
                    ("semibold", "Semibold"),
                    ("bold", "Bold"),
                    ("black", "Black"),
                ],
                default="semibold",
                max_length=20,
                verbose_name="title weight",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="background_color",
            field=models.CharField(
                default="#00E5FF",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Date and time when this record was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Display order. Lower values appear first.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="text_color",
            field=models.CharField(
                default="#000000",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use a hex color such as #00E5FF or #FFF.",
                        regex="^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$",
                    )
                ],
                verbose_name="text color",
            ),
        ),
        migrations.AlterField(
            model_name="promobanner",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when this record was last updated.",
                verbose_name="updated at",
            ),
        ),
    ]
