# Generated by Django 5.2.14 on 2026-09-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogitem_vendor'),
        ('content', '0012_promobanner_background_color_secondary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Optional product photo shown on the discount banner.',
                null=True,
                upload_to='content/promos/',
                verbose_name='product photo',
            ),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='image_item',
            field=models.ForeignKey(
                blank=True,
                help_text='Catalog product whose photo is shown when no custom image is uploaded.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='promo_banner_photos',
                to='catalog.catalogitem',
                verbose_name='product photo source',
            ),
        ),
    ]
