# Generated by Django 5.2.10 on 2026-01-21 08:22

import apps.quotes.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable quote number (folio).",
                        max_length=20,
                        unique=True,
                        verbose_name="quote number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("converted", "Converted to Order"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current quote status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quote version number.",
                        verbose_name="version",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer's name.",
                        max_length=255,
                        verbose_name="customer name",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer's email for notifications.",
                        max_length=254,
                        verbose_name="customer email",
                    ),
                ),
                (
                    "customer_company",
                    models.CharField(
                        blank=True,
                        help_text="Customer's company.",
                        max_length=255,
                        verbose_name="customer company",
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=apps.quotes.models.get_default_validity_date,
                        help_text="Quote validity date.",
                        verbose_name="valid until",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quote subtotal before tax.",
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1600"),
                        help_text="Applied tax rate.",
                        max_digits=5,
                        verbose_name="tax rate",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount.",
                        max_digits=12,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quote total.",
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN",
                        help_text="Currency code.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("FULL", "Full"), ("DEPOSIT_ALLOWED", "Deposit")],
                        default="FULL",
                        help_text="Payment requirements.",
                        max_length=20,
                        verbose_name="payment mode",
                    ),
                ),
                (
                    "deposit_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deposit percentage if applicable.",
                        max_digits=5,
                        null=True,
                        verbose_name="deposit percentage",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        blank=True,
                        help_text="Commercial terms and conditions.",
                        verbose_name="commercial terms",
                    ),
                ),
                (
                    "terms_en",
                    models.TextField(
                        blank=True,
                        help_text="Terms in English.",
                        verbose_name="commercial terms (English)",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Staff notes (not visible to customer).",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Secure access token for customer link.",
                        unique=True,
                        verbose_name="access token",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF file.",
                        null=True,
                        upload_to="quotes/pdfs/",
                        verbose_name="PDF file",
                    ),
                ),
                (
                    "pdf_file_en",
                    models.FileField(
                        blank=True,
                        help_text="English PDF file.",
                        null=True,
                        upload_to="quotes/pdfs/",
                        verbose_name="PDF file (English)",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When quote was sent to customer.",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer first viewed quote.",
                        null=True,
                        verbose_name="viewed at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer accepted quote.",
                        null=True,
                        verbose_name="accepted at",
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer rejected quote.",
                        null=True,
                        verbose_name="rejected at",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        help_text="Primary language for quote.",
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Sales rep who created quote.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quote",
                "verbose_name_plural": "quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "concept",
                    models.CharField(
                        help_text="Line item concept/name.",
                        max_length=255,
                        verbose_name="concept",
                    ),
                ),
                (
                    "concept_en",
                    models.CharField(
                        blank=True,
                        help_text="Concept in English.",
                        max_length=255,
                        verbose_name="concept (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description.",
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description in English.",
                        verbose_name="description (English)",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity.",
                        max_digits=10,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="pz",
                        help_text="Unit of measure (pz, m², kg, etc.).",
                        max_length=20,
                        verbose_name="unit",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit.",
                        max_digits=12,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line total.",
                        max_digits=12,
                        verbose_name="line total",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order.", verbose_name="position"
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source product/service.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="catalog.catalogitem",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Parent quote.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote line",
                "verbose_name_plural": "quote lines",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable request number.",
                        max_length=20,
                        unique=True,
                        verbose_name="request number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("info_requested", "Info Requested"),
                            ("quoted", "Quote Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current request status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer's full name.",
                        max_length=255,
                        verbose_name="customer name",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer's email address.",
                        max_length=254,
                        verbose_name="customer email",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Customer's phone number.",
                        max_length=20,
                        verbose_name="customer phone",
                    ),
                ),
                (
                    "customer_company",
                    models.CharField(
                        blank=True,
                        help_text="Customer's company name.",
                        max_length=255,
                        verbose_name="customer company",
                    ),
                ),
                (
                    "catalog_item_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of requested item (preserved if item deleted).",
                        max_length=255,
                        verbose_name="item name",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Requested quantity.",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text='Requested dimensions (e.g., "3x2m").',
                        max_length=100,
                        verbose_name="dimensions",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Requested material.",
                        max_length=100,
                        verbose_name="material",
                    ),
                ),
                (
                    "includes_installation",
                    models.BooleanField(
                        default=False,
                        help_text="Whether installation is requested.",
                        verbose_name="includes installation",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details and requirements.",
                        verbose_name="description",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Customer's IP address.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Customer's browser/device info.",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        help_text="Preferred language for communication.",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales rep assigned to this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_quote_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Requested product/service.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to="catalog.catalogitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (if logged in).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quote request",
                "verbose_name_plural": "quote requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file.",
                        upload_to="quotes/attachments/",
                        verbose_name="file",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename.",
                        max_length=255,
                        verbose_name="filename",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type.",
                        max_length=100,
                        verbose_name="file type",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Size in bytes.", verbose_name="file size"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="File description.",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source quote.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="quotes.quote",
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source quote request.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="quotes.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote attachment",
                "verbose_name_plural": "quote attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="quote_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Source quote request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="quotes.quoterequest",
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["request_number"], name="quotes_quot_request_51d1e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["status", "created_at"], name="quotes_quot_status_13321e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["assigned_to", "status"], name="quotes_quot_assigne_a6fdbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["customer_email"], name="quotes_quot_custome_dc49b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_number"], name="quotes_quot_quote_n_6770d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["token"], name="quotes_quot_token_387f12_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "valid_until"], name="quotes_quot_status_3ae330_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["customer_email"], name="quotes_quot_custome_410dd6_idx"
            ),
        ),
    ]
