# Generated by Django 5.2.10 on 2026-02-05 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="customer_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes visible to customer.",
                verbose_name="customer notes",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_time_text",
            field=models.CharField(
                blank=True,
                help_text='Human-readable delivery time (e.g., "10 business days").',
                max_length=100,
                verbose_name="delivery time text",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated delivery date.",
                null=True,
                verbose_name="estimated delivery date",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="first_view_at",
            field=models.DateTimeField(
                blank=True,
                help_text="First time customer viewed quote.",
                null=True,
                verbose_name="first view at",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="included_services",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Services included in the quote.",
                verbose_name="included services",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="last_view_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time customer viewed quote.",
                null=True,
                verbose_name="last view at",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_conditions",
            field=models.TextField(
                blank=True,
                help_text="Payment conditions and terms.",
                verbose_name="payment conditions",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="payment_methods",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Accepted payment methods.",
                verbose_name="payment methods",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times quote was viewed.",
                verbose_name="view count",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the request was assigned.",
                null=True,
                verbose_name="assigned at",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="assignment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("auto_specialty", "Automatic by Specialty"),
                    ("auto_load", "Automatic by Load"),
                    ("fallback", "Fallback"),
                ],
                help_text="How the request was assigned.",
                max_length=20,
                verbose_name="assignment method",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="is_guest",
            field=models.BooleanField(
                default=True,
                help_text="Whether customer is a guest (not registered).",
                verbose_name="is guest",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="required_date",
            field=models.DateField(
                blank=True,
                help_text="Date when customer needs the service.",
                null=True,
                verbose_name="required date",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="service_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dynamic service-specific details from landing form.",
                verbose_name="service details",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="service_type",
            field=models.CharField(
                blank=True,
                help_text="Type of service requested (from landing form).",
                max_length=100,
                verbose_name="service type",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="urgency",
            field=models.CharField(
                choices=[("normal", "Normal"), ("medium", "Medium"), ("high", "High")],
                default="normal",
                help_text="Request urgency (calculated from required_date).",
                max_length=10,
                verbose_name="urgency",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Assignment"),
                    ("assigned", "Assigned"),
                    ("in_review", "In Review"),
                    ("info_requested", "Info Requested"),
                    ("quoted", "Quote Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Current request status.",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="GuestAccessToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique secure token.",
                        max_length=64,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Guest's email address.",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("view_quote", "View Quote"),
                            ("respond_quote", "Respond to Quote"),
                        ],
                        default="respond_quote",
                        help_text="Type of access allowed.",
                        max_length=20,
                        verbose_name="token type",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When token expires.", verbose_name="expires at"
                    ),
                ),
                (
                    "used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether token has been used.",
                        verbose_name="used",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When token was used.",
                        null=True,
                        verbose_name="used at",
                    ),
                ),
                (
                    "ip_used",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when token was used.",
                        null=True,
                        verbose_name="IP used",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated quote.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_tokens",
                        to="quotes.quote",
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated quote request.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_tokens",
                        to="quotes.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "guest access token",
                "verbose_name_plural": "guest access tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="quotes_gues_token_10eedb_idx"),
                    models.Index(fields=["email"], name="quotes_gues_email_81aa74_idx"),
                    models.Index(
                        fields=["expires_at", "used"],
                        name="quotes_gues_expires_c2811a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuoteResponse",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("comment", "Commented"),
                            ("change_request", "Change Request"),
                            ("approval", "Approved"),
                            ("rejection", "Rejected"),
                        ],
                        help_text="Type of response.",
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Customer's comment.",
                        verbose_name="comment",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        help_text="Guest name (if not registered).",
                        max_length=255,
                        verbose_name="guest name",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        blank=True,
                        help_text="Guest email (if not registered).",
                        max_length=254,
                        verbose_name="guest email",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when responding.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Quote being responded to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quotes.quote",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who responded (null if guest).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quote response",
                "verbose_name_plural": "quote responses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["quote", "action"],
                        name="quotes_quot_quote_i_9798f5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="quotes_quot_created_6f2a7b_idx"
                    ),
                ],
            },
        ),
    ]
