# Generated by Django 5.2.10 on 2026-02-06 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_add_quote_system_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("viewed", "Viewed"),
                    ("changes_requested", "Changes Requested"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("converted", "Converted to Order"),
                ],
                db_index=True,
                default="draft",
                help_text="Current quote status.",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="QuoteChangeRequest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Request status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        help_text="Customer name (copied from quote).",
                        max_length=255,
                        verbose_name="customer name",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email (copied from quote).",
                        max_length=254,
                        verbose_name="customer email",
                    ),
                ),
                (
                    "customer_comments",
                    models.TextField(
                        blank=True,
                        help_text="Customer explanation for requested changes.",
                        verbose_name="customer comments",
                    ),
                ),
                (
                    "proposed_lines",
                    models.JSONField(
                        default=list,
                        help_text='\n            Array of proposed line items. Each item contains:\n            - id: Original line ID (null for new lines)\n            - action: "modify", "add", or "delete"\n            - concept: Item concept/name\n            - description: Item description\n            - quantity: Proposed quantity\n            - unit: Unit of measure\n            - unit_price: Price per unit (may be null, sales will set)\n            - original_values: Original values for modified lines\n        ',
                        verbose_name="proposed lines",
                    ),
                ),
                (
                    "original_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of original quote state for comparison.",
                        verbose_name="original snapshot",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When request was reviewed.",
                        null=True,
                        verbose_name="reviewed at",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Sales rep notes on the review.",
                        verbose_name="review notes",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Customer IP when submitting.",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Quote being modified.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="quotes.quote",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales rep who reviewed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quote change request",
                "verbose_name_plural": "quote change requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["quote", "status"],
                        name="quotes_quot_quote_i_bb4606_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="quotes_quot_status_2fabcd_idx",
                    ),
                ],
            },
        ),
    ]
