# Generated by Django 5.2.11 on 2026-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_add_quote_change_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                help_text="Customer signature image captured on acceptance.",
                null=True,
                upload_to="quotes/signatures/",
                verbose_name="signature image",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="signature_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="signer name"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="signed at"),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Assignment"),
                    ("assigned", "Assigned"),
                    ("in_review", "In Review"),
                    ("quoted", "Quote Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Current request status.",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
