# Generated by Django 5.2.11 on 2026-02-09 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quote_signature_image_quote_signature_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                help_text="Customer's phone number.",
                max_length=20,
                verbose_name="customer phone",
            ),
        ),
        migrations.AddField(
            model_name="quoteattachment",
            name="change_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Source change request.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="quotes.quotechangerequest",
            ),
        ),
    ]
