# Generated by Django 5.2.10 on 2026-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_quote_customer_phone_quoteattachment_change_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteline",
            name="service_details",
            field=models.JSONField(
                blank=True,
                help_text="Structured service-specific fields (type, dimensions, routes, etc.).",
                null=True,
                verbose_name="service details",
            ),
        ),
    ]
