# Generated by Django 5.2.11 on 2026-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0006_add_service_details_to_quoteline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteresponse",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "Viewed"),
                    ("comment", "Commented"),
                    ("change_request", "Change Request"),
                    ("approval", "Approved"),
                    ("rejection", "Rejected"),
                    ("send", "Sent"),
                ],
                help_text="Type of response.",
                max_length=20,
                verbose_name="action",
            ),
        ),
    ]
