# Generated by Django 5.2.11 on 2026-02-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_add_service_key_to_service"),
        ("quotes", "0007_alter_quoteresponse_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="delivery_address",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Shipping or installation address.",
                verbose_name="delivery address",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("installation", "Installation on-site"),
                    ("pickup", "Pickup at branch"),
                    ("shipping", "Shipping"),
                    ("digital", "Digital delivery"),
                    ("not_applicable", "Not applicable"),
                ],
                help_text="Selected delivery method.",
                max_length=20,
                verbose_name="delivery method",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="pickup_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch for pickup delivery.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="content.branch",
                verbose_name="pickup branch",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_address",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Delivery/installation address details.",
                verbose_name="delivery address",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("installation", "Installation on-site"),
                    ("pickup", "Pickup at branch"),
                    ("shipping", "Shipping"),
                    ("digital", "Digital delivery"),
                    ("not_applicable", "Not applicable"),
                ],
                help_text="Preferred delivery method.",
                max_length=20,
                verbose_name="delivery method",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="pickup_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch for pickup (if delivery method is pickup).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_requests",
                to="content.branch",
                verbose_name="pickup branch",
            ),
        ),
    ]
