# Generated by Django 5.2.10 on 2026-02-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0008_quote_delivery_address_quote_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteresponse",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Snapshot of the PDF at the time of sending.",
                null=True,
                upload_to="quotes/response_pdfs/",
                verbose_name="PDF file",
            ),
        ),
    ]
