# Generated by Django 5.2.11 on 2026-02-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_quoteresponse_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="info_request_message",
            field=models.TextField(
                blank=True,
                help_text="Message from vendor requesting additional information from the client.",
                verbose_name="info request message",
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="info_request_token",
            field=models.UUIDField(
                blank=True,
                help_text="Unique token for the client to respond to info request.",
                null=True,
                unique=True,
                verbose_name="info request token",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Assignment"),
                    ("assigned", "Assigned"),
                    ("in_review", "In Review"),
                    ("info_requested", "Info Requested"),
                    ("quoted", "Quote Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                help_text="Current request status.",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
