# Generated by Django 5.2.11 on 2026-02-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0010_add_info_requested_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="info_request_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of service_details field keys the vendor flagged for review.",
                verbose_name="info request fields",
            ),
        ),
    ]
