# Generated by Django 5.2.11 on 2026-02-16 01:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_seed_branches"),
        ("quotes", "0011_add_info_request_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteline",
            name="delivery_address",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="delivery address"
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("installation", "Installation on-site"),
                    ("pickup", "Pickup at branch"),
                    ("shipping", "Shipping"),
                    ("digital", "Digital delivery"),
                    ("not_applicable", "Not applicable"),
                ],
                max_length=20,
                verbose_name="delivery method",
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="estimated delivery date"
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="pickup_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_lines",
                to="content.branch",
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Shipping/delivery cost for this line item (no tax applied).",
                max_digits=12,
                verbose_name="shipping cost",
            ),
        ),
        migrations.CreateModel(
            name="QuoteRequestService",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within the request.",
                        verbose_name="position",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of service requested.",
                        max_length=100,
                        verbose_name="service type",
                    ),
                ),
                (
                    "service_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dynamic service-specific details.",
                        verbose_name="service details",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("installation", "Installation on-site"),
                            ("pickup", "Pickup at branch"),
                            ("shipping", "Shipping"),
                            ("digital", "Digital delivery"),
                            ("not_applicable", "Not applicable"),
                        ],
                        max_length=20,
                        verbose_name="delivery method",
                    ),
                ),
                (
                    "delivery_address",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="delivery address"
                    ),
                ),
                (
                    "required_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="required date"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="comments")),
                (
                    "pickup_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_services",
                        to="content.branch",
                        verbose_name="pickup branch",
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        help_text="Parent quote request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="quotes.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote request service",
                "verbose_name_plural": "quote request services",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="quoteattachment",
            name="request_service",
            field=models.ForeignKey(
                blank=True,
                help_text="Source request service (for multi-service requests).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="quotes.quoterequestservice",
            ),
        ),
    ]
