# Generated by Django 5.2.10 on 2026-01-21 08:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates if this record has been soft-deleted.",
                        verbose_name="is deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this record was soft-deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable order number.",
                        max_length=20,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("in_production", "In Production"),
                            ("ready", "Ready"),
                            ("in_delivery", "In Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current order status.",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(
                        default=dict,
                        help_text="Shipping address snapshot.",
                        verbose_name="shipping address",
                    ),
                ),
                (
                    "billing_address",
                    models.JSONField(
                        default=dict,
                        help_text="Billing address snapshot.",
                        verbose_name="billing address",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Order subtotal before tax.",
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1600"),
                        help_text="Applied tax rate (e.g., 0.16 for 16%).",
                        max_digits=5,
                        verbose_name="tax rate",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tax amount.",
                        max_digits=12,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Order total.",
                        max_digits=12,
                        verbose_name="total",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount already paid.",
                        max_digits=12,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN",
                        help_text="Currency code.",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mercadopago", "Mercado Pago"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        help_text="Selected payment method.",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from customer.",
                        verbose_name="customer notes",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for staff (not visible to customer).",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        help_text="Shipment tracking number.",
                        max_length=100,
                        verbose_name="tracking number",
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(
                        blank=True,
                        help_text="Shipment tracking URL.",
                        verbose_name="tracking URL",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was confirmed.",
                        null=True,
                        verbose_name="paid at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When order was completed.",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="SKU at time of order.",
                        max_length=100,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product name at time of order.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "variant_name",
                    models.CharField(
                        blank=True,
                        help_text='Variant details (e.g., "Blue, Large").',
                        max_length=255,
                        verbose_name="variant name",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Ordered quantity.",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at time of order.",
                        max_digits=12,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Line total (quantity * unit_price).",
                        max_digits=12,
                        verbose_name="line total",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional line item data.",
                        verbose_name="metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "order line",
                "verbose_name_plural": "order lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("in_production", "In Production"),
                            ("ready", "Ready"),
                            ("in_delivery", "In Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        help_text="Previous status.",
                        max_length=20,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("in_production", "In Production"),
                            ("ready", "Ready"),
                            ("in_delivery", "In Delivery"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        help_text="New status.",
                        max_length=20,
                        verbose_name="to status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the change.",
                        verbose_name="notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "order status history",
                "verbose_name_plural": "order status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("billing", "Billing")],
                        default="shipping",
                        help_text="Address type.",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default address for this type.",
                        verbose_name="is default",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Recipient name.", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone.", max_length=20, verbose_name="phone"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Street name.", max_length=255, verbose_name="street"
                    ),
                ),
                (
                    "exterior_number",
                    models.CharField(
                        help_text="Exterior number.",
                        max_length=20,
                        verbose_name="exterior number",
                    ),
                ),
                (
                    "interior_number",
                    models.CharField(
                        blank=True,
                        help_text="Interior number.",
                        max_length=20,
                        verbose_name="interior number",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        help_text="Neighborhood (colonia).",
                        max_length=100,
                        verbose_name="neighborhood",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City.", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State.", max_length=100, verbose_name="state"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code.",
                        max_length=10,
                        verbose_name="postal code",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="MEX",
                        help_text="Country code (ISO 3166-1 alpha-3).",
                        max_length=3,
                        verbose_name="country",
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        blank=True,
                        help_text="Delivery reference (landmarks, instructions).",
                        verbose_name="reference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Address owner.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Session key for guest carts.",
                        max_length=40,
                        verbose_name="session key",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Cart owner.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Item quantity.", verbose_name="quantity"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Parent cart.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        help_text="Product variant.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
            },
        ),
    ]
