# Generated by Django 5.2.11 on 2026-02-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_add_service_key_to_service"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Delivery or installation address.",
                verbose_name="delivery address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("installation", "Installation on-site"),
                    ("pickup", "Pickup at branch"),
                    ("shipping", "Shipping"),
                    ("digital", "Digital delivery"),
                    ("not_applicable", "Not applicable"),
                ],
                help_text="Delivery method for this order.",
                max_length=20,
                verbose_name="delivery method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch for pickup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="content.branch",
                verbose_name="pickup branch",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Scheduled date/time for installation or delivery.",
                null=True,
                verbose_name="scheduled date",
            ),
        ),
    ]
