# Generated by Django 5.2.11 on 2026-04-16 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_address_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="operation_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Computed operation plan and dependency map for this order.",
                verbose_name="operation plan",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="operational_rollup",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_execution", "In Execution"),
                    ("awaiting_finalization", "Awaiting Finalization"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                db_index=True,
                default="planned",
                help_text="Aggregated operational progress across production, logistics and field operations.",
                max_length=30,
                verbose_name="operational rollup",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="origin",
            field=models.CharField(
                choices=[
                    ("quote_conversion", "Quote Conversion"),
                    ("direct_purchase", "Direct Purchase"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="direct_purchase",
                help_text="How this order was created (quote conversion or direct purchase).",
                max_length=30,
                verbose_name="origin",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Frozen service-level data used for operational routing.",
                verbose_name="service snapshot",
            ),
        ),
        migrations.CreateModel(
            name="FieldOperationJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("crew_assigned", "Crew Assigned"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("requires_revisit", "Requires Revisit"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=25,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("installation", "Installation"),
                            ("mobile_campaign", "Mobile Campaign"),
                            ("service_window", "Service Window"),
                        ],
                        default="installation",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("location_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_ops_jobs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "field operation job",
                "verbose_name_plural": "field operation jobs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_dispatch", "Pending Dispatch"),
                            ("scheduled", "Scheduled"),
                            ("in_transit", "In Transit"),
                            ("ready_for_pickup", "Ready For Pickup"),
                            ("delivered", "Delivered"),
                            ("delivery_failed", "Delivery Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_dispatch",
                        max_length=25,
                    ),
                ),
                (
                    "logistics_type",
                    models.CharField(
                        choices=[
                            ("shipping", "Shipping"),
                            ("pickup", "Pickup"),
                            ("digital_delivery", "Digital Delivery"),
                        ],
                        default="shipping",
                        max_length=20,
                    ),
                ),
                ("window_start", models.DateTimeField(blank=True, null=True)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("address_snapshot", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_jobs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "logistics job",
                "verbose_name_plural": "logistics jobs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("in_production", "In Production"),
                            ("quality_check", "Quality Check"),
                            ("released", "Released"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("requires_quality_check", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_jobs",
                        to="orders.order",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_jobs",
                        to="orders.orderline",
                    ),
                ),
            ],
            options={
                "verbose_name": "production job",
                "verbose_name_plural": "production jobs",
                "ordering": ["created_at"],
            },
        ),
    ]
